version: "3.9"

services:
  ros2-foxy-ACUK:
    image: ros2-foxy-acuk  # Name of the built image
    container_name: ros2_foxy_acuk
    privileged: true
    network_mode: "host"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - "/dev:/dev"
      - "/sys:/sys"
      - "/lib/modules:/lib/modules"
    environment:
      - ROS_DOMAIN_ID=0  # Set ROS2 domain (if needed)
      - DISPLAY=${DISPLAY} # Allow GUI apps like RViz
    command: ["/bin/bash"]
