services:
  ros2-humble-ACUK:
    image: ros2_humble_acuk  # Name of the built image
    build: .
    container_name: ros2_humble_acuk
    privileged: true
    network_mode: "host"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - "/dev:/dev"
      - "/sys:/sys"
      - "/lib/modules:/lib/modules"
    environment:
      - ROS_DOMAIN_ID=0  # Set ROS2 domain (if needed)
      - DISPLAY=${DISPLAY} # Allow GUI apps like RViz
    command: ["bash", "-c", "tail -f /dev/null"]
